/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/HeaderToolbar copy.vue')['default']
    HeaderSidebar: typeof import('./src/components/HeaderSidebar.vue')['default']
    HeaderToolbar: typeof import('./src/components/HeaderToolbar.vue')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartPage: typeof import('./src/components/StartPage.vue')['default']
    VerhaeltnisRechner: typeof import('./src/components/VerhaeltnisRechner.vue')['default']
    WorkPage: typeof import('./src/components/WorkPage.vue')['default']
  }
}
